name: CPP
on:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'
  pull_request:
    paths:
      - 'cpp/**'
      - '.github/workflows/cpp.yml'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
      - run: cd cpp && make
