name: Python
on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
  pull_request:
    paths:
      - 'python/**'
      - '.github/workflows/python.yml'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python: [ '3.6', '3.7' ]

    steps:
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/checkout@master
    - run: |
          cd python
          pip install -r requirements.txt
          black --check *.py
          python tests.py
